combgsurlnav/urls.py
from django.contrib import admin
from django.urls import path,include
from utube.views import shorts
import utube
from prime.views import movie
import prime

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shorts/',shorts,name='shorts'),
    path('utube/',include('utube.urls')),
     path('movie/',movie,name='movie'),
    path('prime/',include('prime.urls')),

]

prime/urls.py
from django.urls import path
from prime.views import series
app_name='prime'
urlpatterns=[
    path('series/',series,name='series'),
]

utube/urls.py
from django.urls import path
from utube.views import like
app_name='utube'
urlpatterns=[
    path('like/',like,name='like'),
]

prime/models.py
from django.db import models

# Create your models here.

utube/models.py
from django.db import models

# Create your models here.

prime/views.py
from django.shortcuts import render

# Create your views here.
def movie(request):
    return render(request,'movie.html')
def series(request):
    return render(request,'series.html')

utube/views.py
from django.shortcuts import render

# Create your views here.
def shorts(request):
    return render(request,'shorts.html')
def like(request):
    return render(request,'like.html')

templates/like.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is likes page</h1>
        <a href="{% url 'shorts' %}">click here go to shorts page</a>
    </center>
</body>
</html>

templates/movie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            this is the movie page
        </h1>
        <a href="{% url 'prime:series' %}">click here go to series</a>
    </center>
</body>
</html>

templates/series.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is the series page</h1>
        <a href="{% url 'movie' %}">click here for movies page</a>
    </center>
</body>
</html>

templates/shorts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is shorts page</h1>
        <a href="{% url 'utube:like' %}">click here go to like page</a>
    </center>
</body>
</html>